### ISSUE TITLE
Refactor code to work in "long format"

### ISSUE THREAD

**Issue by ns-rse** [Mesnage-Org/pgfinder#104]
In light of #80 and #81 it has been realised that there is some [technical debt](https://en.wikipedia.org/wiki/Technical_debt) in the way the data is structured in the workflow.

Discussion has been made in a few places so this issue pulls things together referencing them so they can be addressed.

Thoughts from @ns-rse are originally [here](https://github.com/Mesnage-Org/pgfinder/issues/81#issuecomment-1157605022) and (see original thread for responses). There is also some discussion in #97.

The consensus that appears to be forming is that addressing this and switching to "long format" whilst working with all the code and reformatting prior to writing CSV is the approach to take.

**Comment by ns-rse** [comment]
The `pgfinder.matching.matching()` function (lines 178-218 of `pgfinder/matching.py`) is where I think we can start addressing this issue.

It makes a copy of the `ftrs_df` and then iterates over each row extracting the `mwMonoisotopic` variable and selecting from the `matching_df` rows where the `Monoisotopicmass` is within the tolerance of this.

This results in a small dataframe of matches from which the `inferredStructure` and `theo_mwMonoisotopic` variables get concatenated into single cells and added to `ftrs_df`.

Instead a `1:n` "left" merge of the original `ftrs_df` could be made to these two columns. Untested but something like the following might work for this function, but I suspect there may well be subsequent steps that need altering too.

```python
def matching(ftrs_df: pd.DataFrame, matching_df: pd.DataFrame, set_ppm: int):
    molecular_weights = list(ftrs_df["mwMonoisotopic"])
    raw_data = ftrs_df.copy()
    for mw in molecular_weights:
        tolerance = calc_ppm_tolerance(mw, set_ppm)
        # Find matches and select just the mass and structure which we rename
        mw_matches = matching_df.loc[(matching_df["Monoisotopicmass"] >= mw - tolerance) & (matching_df["Monoisotopicmass"] <= mw + tolerance), ["Monoisotopicmass", "Structure"]]
        mw_matches.columns = ["theo_mwMonoisotopic", "inferredStructure"]
        # Add the molecular weight in so we can merge
        mw_matches["mw"] = mw
        raw_data = raw_data.merge(mw_matches, how="left", on=["mw"])
    return raw_data
```

**Comment by Ankur-AVP-Patel** [comment]
Okay, I'm working on this and there are 2 issues.

1) The code you've given above gives no matches no matter what I do. I've narrowed down the issue to be with the mw_matches = matching_df.loc.... this returns no matches which is surprising given its fundamentally the same logic as the original matching function expect you've made a list of mono massed from the ftrs_df instead of iterating through it and getting the mono mass from iterrow. I'll looking into why this is and I'm sure it'll be something trivial in the end.

2) Of more concern is that when I'm running the original matching function (in debug mode), the first 2 runs will output a dataframe that doesn't isn't an full copy of the ftrs_df.  Expected behaviour is that even with 0 matches, the output of matching.matching() should provide a dataframe that is the same size as ftrs_df in terms of number of rows (4015) but 2 columns wider (13 ) (for theoMwIsotoptic and inferredStructure) but what I get on the first run is something like 20XX by 13 then the second run will give 3XXX by 13 and the the 3rd run wull give me the full 4015 by 13 dataframe.

I've checked that when ftrs_df is populated by its pgio function that the df contains all the data expected so its not an issue here. I suspect this might be something weird with my setup and editor etc (vscode, anaconda etc). Can someone else try and see if they get the same behaviour just to confirm this isn't some weird inherent issue?

**Comment by Ankur-AVP-Patel** [comment]
```
import pgfinder.matching as matching
import pgfinder.pgio as pgio
import pgfinder.validation as validation
from pgfinder import MULTIMERS, MOD_TYPE, MASS_TO_CLEAN
import pandas as pd
from decimal import *

import timeit
import time

ftrs_filepath = "data/ftrs_test_data.ftrs"
consol_test_data_filepath = "data/maxquant_test_data.txt"
csv_filepath = "data/masses/e_coli_monomer_masses.csv"

masses = pgio.ms_file_reader(ftrs_filepath)
validation.validate_raw_data_df(masses)

theo_masses = pgio.theo_masses_reader(csv_filepath)
validation.validate_theo_masses_df(theo_masses)

savefp = R"C:\Users\ankur\Documents\Test_outputs\test.csv"



mod_test = ['Decay',"Sodium"]

filtered = matching.filtered_theo(masses,theo_masses,10)

variants = matching.modification_generator(filtered,"Decay")

master_list = [
        filtered,
        variants
    ]
theo_masses = pd.concat(master_list)
theo_masses = theo_masses.astype({"Monoisotopicmass": float})


result = matching.matching(masses,theo_masses,10)

# result = result.groupby(["inferredStructure"],as_index=False).first()

# result = matching.clean_up(result,Decimal("203.0793"),0.5)

pd.DataFrame.to_csv(result,savefp)

```

You'll need the above for running so you can debug
