### ISSUE TITLE
myBinder Crashes

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#142]
![image](https://user-images.githubusercontent.com/34244196/232769748-061199b0-6b60-4129-98e8-8abd09e28063.png)

@ns-rse - I feel like I've seen this before.

@smesnage reported this - any more details on what you were doing?

**Comment by ns-rse** [comment]
I've just tried running this using the current "Interactive" notebook with the sample files linked from the Notebook itself and it completes ok.

The errors stems from `data_uploader` (obviously!) which is an object of type `widgets.HBox([file_upload, file_name])` (i.e. an [`ipywidgets.HBox()`](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#hbox)).

And so its returning a `tuple` which is a type of "list". That the index is out of range suggests that nothing is being returned by `data_uploader`.

@smesnage would you be able to share with me the files that are causing this error so I can reproduce and investigate further please.

**Comment by bobturneruk** [comment]
We'd probably need to look at hiding the code - maybe Jupyter Lite supports classic notebooks as well as the current Jupyterlab.

**Comment by smesnage** [comment]
Sounds like progress to me. Let me know if/how I can help!

**Comment by ns-rse** [comment]
If we move to JupyterLite solution we will need to update the `pgfinder_interactive.ipynb` to redirect people to the new alternative.

**Comment by ns-rse** [comment]
I'm coming full circle and think this might be related to #48 which set the upload file limit.

I can reproduce the error locally if I start the notebook _without_ passing it the `jupyter_notebook_config.py`

If I start it with this file it works...

```
jupyter notebook --config jupyter_notebook_config.py ./pgfinder_interactive.ipynb
```

This thread [Binder configuration for large ipywidget file upload](https://discourse.jupyter.org/t/binder-configuration-for-large-ipywidget-file-upload/4662) suggests the configuration file needs to reside under `.jupyter/` to work.

**Comment by ns-rse** [comment]
Progress! I've moved the location of the Jupyter Notebook configuration file that permits "large" files (of up to 100Mb) to be uploaded (`jupyter_notebook_config.py` > ~/.jupyter/jupyter_notebook_config.py`) on branch `ns-rse/colab` (was tinkering with running the code on Google CoLab as an alternative to MyBiner) and had a go at uploading the `.ftrs` file using a Notebook started on that branch (see [here](mybinder.org/v2/gh/Mesnage-Org/PGFinder/ns-rse/colab?urlpath=tree/pgfinder_interactive.ipynb)). For once I paused (was distracted!) and after a short while the file uploaded as shown below....

![image](https://user-images.githubusercontent.com/17566406/235417534-8dfc963c-a3a3-40f5-af2e-718a426c9c8a.png)


Waiting for that file to upload is necessary otherwise the reported error will occur when trying to run the analysis because the `.ftrs` file won't have be available to run. Sure enough we can complete the analysis...

![image](https://user-images.githubusercontent.com/17566406/235417819-932fbb4b-5b38-449b-889f-b0e466dc9cc9.png)

[results_2023-05-01_06-39-25.csv](https://github.com/Mesnage-Org/pgfinder/files/11363938/results_2023-05-01_06-39-25.csv)

Now it could be one of two reasons this has worked...

a) Moving configuration file.
b) Waiting long enough for the file to upload.

To check b) I returned to the [`current`](https://mybinder.org/v2/gh/Mesnage-Org/PGFinder/master?urlpath=tree/pgfinder_interactive.ipynb) Notebook linked from the repositories `README.md` and uploaded the file waiting for five minutes to see if the file actually completed uploading. No dice, the file didn't upload which rules that out and suggests the problem arose because the configuration file was no longer being picked up and that moving the location of the config file has resolved this.

One small possibility that I'm not sure how to investigate is that Binder builds images and stores them in cache and there may be some quirk with the cached version that is causing this problem but I have no idea how to clear the cache and force a rebuild of the `master` other than updating the commit at `HEAD` of the `master` branch (by merging changes in).

**Comment by smesnage** [comment]
TREMENDOUS! Well done detective Shephard. I don't know how you manage to keep your self control with this kind of crap. It's frustrating that no one (but ourselves!!) will realize how much work there is behind this bloody notebook. But it's definitely worth it because I think this makes the difference between a script only used by geeks and a script for the uneducated masses.
Glad to hear it will be up and running before reviewers start clicking on the link.

Can we redirect the following link to the new location? It takes forever for mybinder to load so if people have to wait until they get the message saying it's moved, it's a waste of time. Does this make sense?
https://mybinder.org/v2/gh/Mesnage-Org/PGFinder/master?filepath=pgfinder_interactive.ipynb
