### ISSUE TITLE
Remove hard coded variables to config file

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#73]
E.g. https://github.com/Mesnage-Org/pgfinder/blob/6c2ddb2d93fe90dfc1ba485e29fef3ac1923f1d5/pgfinder/matching.py#L43

**Comment by smesnage** [comment]
Has Neil done this?

**Comment by bobturneruk** [comment]
I'd say not. We have lines like:

https://github.com/Mesnage-Org/pgfinder/blob/1a658bfc29b47e32ac6db5bd1baefd2dcabcbe22/pgfinder/matching.py#L113

These masses would probably be best in a data file. Sorry for the terribly terse issue description, by the way.

**Comment by ns-rse** [comment]
There is Pull Request #97 which addresses this  (in essence this issue is the same as #7). I've finally resolved today after much hair-pulling last night and today (the problem stemmed from an area completely different to what I expected based on the changes I made so involved me digging through to find it).
