### ISSUE TITLE
Minor formatting changes for output

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#81]
Add THREE spaces after the comma to describe multiple theoretical masses and structures matched to observed MS data.
If possible, display Intensity in scientific format.
These changes can be made available to public

**Comment by TheLostLambda** [comment]
![image](https://user-images.githubusercontent.com/6251883/173883594-5032c17f-2449-4b25-89a2-3d9946d55012.png)
I'll look into scientific notation later tonight or tomorrow!

**Comment by TheLostLambda** [comment]
Would I be able to steal write access for branches from @Ankur-AVP-Patel ?
![image](https://user-images.githubusercontent.com/6251883/173885615-46b4baff-7ccf-46ba-9869-bacf429f1f70.png)

**Comment by bobturneruk** [comment]
@TheLostLambda - probably best if you have a chat with me and / or @ns-rse on how we use git in this repo before making changes. Can you drop us an email, please?

**Comment by smesnage** [comment]
It seems sensible to make sure everyone is on the same page before another person chips in!
Based on what Brooks did so far, I'm pretty confident he'll be a very useful addition to the collective brain power.

**Comment by ns-rse** [comment]
Putting some thoughts down here for discussion when we next eet.

As I've been looking at the code in greater detail I feel there are some broader issues that might be worth addressing in the format of output that would help avoid what is known as [technical debt](https://en.wikipedia.org/wiki/Technical_debt).

One of these, which I feel the addition of three spaces between multiple theoretical matches is trying to address, is the way in which output is structured.

Currently it is in a kind of hybrid "wide format", with multiple matches concatenated into a single string across a number of cells. This makes it awkward to read since there is a cognitive burden reading a row with cells like 

| theo_mwMonoisotopic  | InferredStructure        |
|:---------------------|:--------------------------|
|123.45,146.789,146.852|ag-X-1,ag-X-2,ag-X-3|

..and the suggestion in this issue is to split that with spaces 
| theo_mwMonoisotopic  | InferredStructure        |
|:---------------------|:-------------------------|
|123.45,146.789,146.852|ag-X-1,   ag-X-2,   ag-X-3|
  
An alternative which avoids having to do this addition of spaces after commas for multiple columns (and the #80 issue would introduce at least one other cell where this is required) is to refactor the code to avoid this "technical debt" and instead produce what is known as "long format" data. This would, for the above example, result in three rows, one for each possible match...

| theo_mwMonoisotopic  | InferredStructure        |
|----------------------+--------------------------|
|123.45|ag-X-1|
|146.789|ag-X-2|
|146.852|ag-X-3|

...which to my mind is considerably easier to read (this may be an artifact of having worked with such issues in the past many times and opted for this solution regularly).

Its related to the concept of "Tidy Data" which is discussed in[1] and there are some examples in [2] and [3] although here instead of having separate columns in the resulting CSV file the multiple matches are concatenated to strings. This then makes it slightly awkward to do calculations such as delta-PPM requested in #80 because what should be a simple mathematical calculation between two arrays becomes a bit more messy because you have to split the string into its components and do the calculation.

With the way the code is currently structured this could be done earlier in the processing but its again a bit messy. The length of that string can vary by row since one row may have one match, another two, yet another three. This in turn becomes very inefficient in terms of computational time compared as you loop over rows rather than calculating using arrays which are very fast.


If the output format that exists must be adhered to then it should be constructed write at the very end of the processing (which is all done in "long format") after all calculations have been done to avoid having to work round such problems.


[1] [Tidy Data | Journal of Statistical Software](https://www.jstatsoft.org/article/view/v059i10)
[2] [Statology | Long vs Wide data](https://www.statology.org/long-vs-wide-data/)
[3] [Long and Wide Formats in Data, Explained | Towards Data Science](https://towardsdatascience.com/long-and-wide-formats-in-data-explained-e48d7c9a06cb)

**Comment by smesnage** [comment]
All this makes sense. Maybe worth taking a few examples and try to change the format output taking what @ns-rse said into account. Can't figure out what it would look like. Very good point, I'll have a think.

**Comment by ns-rse** [comment]
Pending #104

**Comment by ns-rse** [comment]
I think with the long-format data that @Ankur-AVP-Patel and @TheLostLambda introduced and the review and merging of #141 (which addresses #80) that this can be closed.

There are improvements that can be made to the output data in terms of column headings (see #144 ) and a couple of other issues that may be improvements (sorting the output based on ID ; removing rows where there are no matches perhaps), but these will be separate issues/feature branches.
